# SET WORKING DIRECTORY
wdpath<-"D:\\Data\\Maps\\CBS_Vierkant_data"
setwd(wdpath)


# Load the data generated by 01GenerateData.R
plot.data <- read.csv("GeneratedData/NL500m.csv", header=TRUE, stringsAsFactors=FALSE)

plot(10,10)
xkcd_line <- function(x, y, color, lwd) {
  len <- length(x);
  rg <- par("usr");
  yjitter <- (rg[4] - rg[3]) / 2000;
  xjitter <- (rg[2] - rg[1]) / 2000;
  x_mod <- x + rnorm(len) * xjitter;
  y_mod <- y + rnorm(len) * yjitter;
  #lines(x_mod, y_mod, col='white', lwd=10);
  lines(x_mod, y_mod, col=color, lwd=lwd);
}


# Add padding above/below where there was data

On top
top.padding <- 1:10
for (i in top.padding) {
  plot.data <- cbind(0, plot.data)
}
# On bottom
bottom.padding <- 1:10
for (i in bottom.padding) {
  plot.data <- cbind(plot.data, 0)
}

On left
zero.row <- vector(mode="integer", length=dim(plot.data)[1])

left.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(zero.row, plot.data)
}

# On right
right.padding <- 1:10
for (i in left.padding) {
  plot.data <- rbind(plot.data, zero.row)
}


max <- max(plot.data) # Max value in the data, used for scaling
plottingHeight <- 2000 # Arbitrary number that provides the graph's height
scaleFactor <- 200 # Discovered through trial and error to keep the graph in the boundaries
gap <- plottingHeight / length(plot.data) # Space between lines
#gap<-50
# Used for splines since sometimes they can return negative values
zeroNegatives <- function(x) {
  if (x < 0) { 
    return (0) 
  } else { 
    return (x) 
  }
}
pdf("JD2.pdf")
par(bg = "black") 
# Create a blank plot
yVals <- as.vector(plot.data[[1]] / max * scaleFactor)
#plot(0, 0, xlim=c(0, length(spline(1:length(yVals), yVals)$y)), ylim=c(0,1500), type="n", las=1, xlab=NA, ylab=NA, bty="n", axes=FALSE)
plot(0, 0, xlim=c(0, length(spline(1:length(yVals), yVals)$y)), ylim=c(0,2000), type="n", las=1, xlab=NA, ylab=NA, bty="n", axes=FALSE, col="black")

plotting.threshold <- 0.2

for (i in 1:length(plot.data)) {  
  # Grabs a row of data
  yVals <- as.vector(plot.data[[i]] / max * scaleFactor)
  
  yValsSmoothed <- spline(1:length(yVals), yVals)$y
  yValsSmoothed <- sapply(yValsSmoothed, zeroNegatives)
  
  xValsSmoothed <- c(0, 0:(length(yValsSmoothed) - 1), length(yValsSmoothed))
  yValsSmoothed <- c(plottingHeight, yValsSmoothed + plottingHeight, plottingHeight)
  
  polygon(x = xValsSmoothed, y = yValsSmoothed, border = NA, col = "black")
  #polygon(x = xValsSmoothed, y = yValsSmoothed, border = NA, col = "#ffffff")
  #lines(x = xValsSmoothed, y = yValsSmoothed, col="#cccccc", lwd=1.5)
  #lines(x = xValsSmoothed, y = yValsSmoothed, col="white", lwd=1)
  xkcd_line(x = xValsSmoothed, y = yValsSmoothed, col="white", lwd=1)
  # Plot the peaks with a darker line
  j <- 2 # Skip padding
  while (j <= (length(yValsSmoothed) - 2)) {
    
    if ((yValsSmoothed[j] - plottingHeight) > plotting.threshold | (yValsSmoothed[j+1] - plottingHeight) > plotting.threshold) {
      segments(xValsSmoothed[j], yValsSmoothed[j], xValsSmoothed[j+1], yValsSmoothed[j+1], col="white", lwd=1)
    } else { } # Do nothing 
    
    j <- j + 1
    
  }
  
  plottingHeight <- plottingHeight - gap
}

dev.off()
